import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const gilroy = localfont({
  src: [
    {
      path: "../../public/fonts/Gilroy-Bold.woff",
      weight: "700",
    }
    ,
    {
      path: "../../public/fonts/Gilroy-Heavy.woff",
      weight: "900",
    },
    {
      path: "../../public/fonts/Gilroy-Regular.woff",
      weight: "400",
    },
    {
      path: "../../public/fonts/Gilroy-Medium.woff",
      weight: "500",
    },
    {
      path: "../../public/fonts/Gilroy-Light.woff",
      weight: "300",
    }
  ],
  variable: "--font-gilroy",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
